### PR TITLE
Bug 1797133: cherry-pick pkg/certagent: add support for passing escaped IPv6 addresses

### PR DESCRIPTION
**Pull request by hexfusion**
Cherry pick of https://github.com/coreos/kubecsr/pull/31

### CODE REVIEW

**Comment by hexfusion** [comment]
I will get the bug in a bit

**Comment by hexfusion** [comment]
>level=fatal msg="failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed to apply using Terraform"

/test e2e-aws

**Comment by wking** [comment]
Did you mean to delete the branch?  This hadn't landed yet.

**Comment by hexfusion** [comment]
lol

**Pull request merged**
